### ISSUE TITLE
v1.0.0 is incompatible with backbone-super

### ISSUE THREAD

**Issue by far-blue** [Volicon/backbone.nestedTypes#98]
I'm a great fan of NestedTypes and love the additional functionality it brings. But I'm currently prevented upgrading from v0.10.0 to v1.0.0 because when I tried it breaks the backbone-super plugin that I also make extensive use of. Would it be possible to identify why the plugins clash and create a fix to allow them to co-operate? Or maybe it would be possible to supply the functionality in NestedTypes instead?

**Comment by gaperton** [comment]
It breaks because backbone-super overrides Model.extend.

https://github.com/lukasolson/backbone-super/blob/master/backbone-super/backbone-super.js

Starting from version 1.0.0, NestedTypes is not using Backbone's `extend` any more.

> Or maybe it would be possible to supply the functionality in NestedTypes instead?

It's theoretically possible, however, since of arrival of ES6 standard (with classes and convenient super) it doesn't make too much sense investing in opinionated proprietary OO libraries.

I'm planning to add ES6 classes support soon. However, you can add support for this plugin yourself in your custom build.

`Extend` function is decoupled from the rest of the library and implemented in this file. 
https://github.com/Volicon/backbone.nestedTypes/blob/master/src/object%2B.js

Modify it. Then, do `npm install` and `npm run build`. That's it.
