### ISSUE TITLE
Please specify which versions of Backbone are compatible

### ISSUE THREAD

**Issue by far-blue** [Volicon/backbone.nestedTypes#99]
It would be very helpful to know which versions of Backbone are compatible with/tested with each release.

**Comment by gaperton** [comment]
All 1.X.X should work fine. Will add it to the documentation. It very likely will work with 0.X.X too.

**Comment by gaperton** [comment]
Just tried to upgrade backbone to 1.2, and noticed weird bugs in new collections implementation. Playful little hands recently touched them just for fun.

I'm a bit tired of that surprised. In next version, I will make my own implementation of core mechanics of collections and events. For now, 1.1.X is known to be safe - tested with our codebase.

**Comment by gaperton** [comment]
Ok, last version doesn't require backbone. Stable 1.1.X version is linked in. Proven to be stable on our 100K code base. Enjoy. Keep in mind, that package name is changed. `npm install nestedtypes`

**Comment by far-blue** [comment]
So does this mean NestedTypes is now a 100% replacement for Backbone? Is the plan to maintain compatibility with Backbone in the same way LowDash mostly does with Underscore?

**Comment by gaperton** [comment]
Yes and no. Yes, because technically it extends Backbone namespace, and I keep core behavior of the models as close as possible to Backbone (model's internal structure is untouched). Many plugins and frameworks will work (chaplinjs and backbone.pageable in our case).

No, because there are some serious architectural differences, causing approaches working for backbone not to work with nestedtypes. For example, you cannot use NestedTypes models as dictionary or map - all attributes must be declared in advance, otherwise it can't do its magic. You should not use function as defaults body - it supposed to be type spec. Any plugin assuming Model.extend is the same as Collection.extend, and trying to mess with .extend mechanics will fail (there are some).

It also behaves a bit differently in little aspects and boundary conditions, which are not really documented. For example, when you create collection with a list of elements as an argument, in backbone case collection will appear empty inside of its initialize. In NestedTypes it will be already populated with elements (which you probably expect).
